# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.CharField(max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GasThemeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('gas_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GasTheme')),
            ],
            options={
                'verbose_name_plural': 'gas_theme_comments',
            },
        ),
        migrations.CreateModel(
            name='GasThemeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=3)),
                ('title', models.CharField(default='no', max_length=50)),
                ('subtitle', models.CharField(default='no', max_length=50)),
                ('text', models.TextField(default='no')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='pictures')),
                ('photo_text', models.CharField(default='no', max_length=300)),
                ('photo2', models.ImageField(blank=True, upload_to='pictures')),
                ('photo2_text', models.CharField(default='no', max_length=300)),
                ('photo3', models.ImageField(blank=True, upload_to='pictures')),
                ('photo3_text', models.CharField(default='no', max_length=300)),
                ('gas_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GasTheme')),
            ],
            options={
                'verbose_name_plural': 'gas_theme_textes',
            },
        ),
        migrations.CreateModel(
            name='GasTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GasTopicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('gas_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GasTopic')),
            ],
            options={
                'verbose_name_plural': 'gas_topic_comments',
            },
        ),
        migrations.CreateModel(
            name='GasTopicText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='pictures')),
                ('photo_text', models.CharField(default='no', max_length=300)),
                ('photo2', models.ImageField(blank=True, upload_to='pictures')),
                ('photo2_text', models.CharField(default='no', max_length=300)),
                ('photo3', models.ImageField(blank=True, upload_to='pictures')),
                ('photo3_text', models.CharField(default='no', max_length=300)),
                ('gas_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GasTopic')),
            ],
            options={
                'verbose_name_plural': 'gas_topic_textes',
            },
        ),
    ]
