# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180217_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastheme',
            name='sub_text',
            field=models.CharField(default='subtext', max_length=200),
            preserve_default=False,
        ),
    ]
