# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 20:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_photoalbum_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures')),
                ('text', models.CharField(default='text', max_length=200)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2018, 3, 1, 20, 33, 9, 875534, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 20, 33, 9, 859934, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='photo',
            name='photoalbum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.PhotoAlbum'),
        ),
    ]
