# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180301_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 21, 10, 26, 64537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 21, 10, 26, 64537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
