# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180303_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastopic',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 19, 9, 36, 415701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 19, 9, 36, 415701, tzinfo=utc)),
        ),
    ]
