# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20180304_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasThemeCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('gasthemecomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GasThemeComment')),
            ],
            options={
                'verbose_name_plural': 'gas_theme_comments_replyies',
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 20, 35, 26, 122739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 20, 35, 26, 122739, tzinfo=utc)),
        ),
    ]
